# Generated by Django 4.2.2 on 2023-07-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_withdrawmodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeedmodel',
            name='image',
            field=models.FileField(default=1, upload_to='bankapp/static'),
            preserve_default=False,
        ),
    ]
